apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: slugterra-alerts
        rules:
          - alert: HighApiLatencyP95
            expr: histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le)) > 0.5
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "P95 API latency is above 500ms"

          - alert: High5xxErrorRate
            expr: sum(rate(django_http_responses_total_by_status_total{status=~"5.."}[5m])) / clamp_min(sum(rate(django_http_responses_total_by_status_total[5m])), 1) > 0.05
            for: 3m
            labels:
              severity: critical
            annotations:
              summary: "5xx ratio exceeded 5 percent"
