apiVersion: apps/v1
kind: Deployment
metadata:
  name: slugapp
  namespace: slugapi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slugapp
  template:
    metadata:
      labels:
        app: slugapp
    spec:
      containers:
      - name: slugapp
        image: harshchauhan01/slug-api:latest
        imagePullPolicy: IfNotPresent
        command: ["gunicorn"]
        args:
        - "config.wsgi:application"
        - "--bind"
        - "0.0.0.0:8000"
        - "--workers"
        - "3"
        - "--timeout"
        - "60"
        - "--access-logfile"
        - "-"
        - "--error-logfile"
        - "-"
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: DJANGO_DEBUG
        - name: ENABLE_RATE_LIMITING
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: ENABLE_RATE_LIMITING
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: DJANGO_ALLOWED_HOSTS
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: slugapp-secret
              key: DJANGO_SECRET_KEY
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: slugapp-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: POSTGRES_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: slugapp-config
              key: REDIS_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
