apiVersion: v1
kind: Secret
metadata:
  name: slugapp-secret
  namespace: slugapi-ns
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-this-in-cluster"
  POSTGRES_PASSWORD: "change-this-in-cluster"
