apiVersion: v1
kind: Secret
metadata:
  name: slugapp-secret
  namespace: slugapi-ns
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "k818!hc%)cc66&hst)nl+%3@o)w8l35+h4@kpv8d6i(uce!b%5"
  POSTGRES_PASSWORD: "change-this-in-cluster"
