apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: slugapp-alert-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: slugapp
      rules:
        - alert: SlugAppPodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total{namespace="slugapi-ns", pod=~"slugapp-.*"}[1h]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "SlugApp pod restarting frequently"
            description: "A SlugApp pod restarted more than three times in the last hour."
